### ISSUE TITLE
MINOR: Budget Calculation Issue

### ISSUE THREAD

**Issue by ShrutiR5** [BeckMillet/INFO442Team5#48] opened 2020-06-04 00:03 UTC
**Describe the bug**

**UPDATE/Disclaimer**: **The update! button wasn't very clear therefore made me think this was a functionality bug initially, but it's a design issue.** Ref. comment for more details. 

After entering a budget and then entering a transaction (returning users), the overall budget does not update accordingly to new transactions if the daily budget is updated once again before entering them. 

**To Reproduce**
1. Go to budget and add $30.
2. Scroll down and add item name and $ amount as $30.00.
3. Click submit
4. Go back up to budget and change budget to $50.
5. Add a new item with amount $20.
6. See error in calculated total of remainder funds being $-20.00. 

**Expected behavior**
If the budget is updated for a given day, the new added item/amount should change according to new budget not old budget. 

**Screenshot**
<img width="226" alt="Screen Shot 2020-06-03 at 5 16 22 PM" src="https://user-images.githubusercontent.com/35204568/83701278-05544700-a5be-11ea-9bdc-7344eee9b551.png">

**Smartphone (please complete the following information):**
 - Device: iPhoneX 

**Additional context**
N/A

**Comment by thoalala** [comment] 2020-06-04 00:13
@ShrutiR5 Cannot reproduce. A screenshot would be super helpful :). Thanks for being thorough while testing btw! 
-  I added $30 to my daily budget.
- Entered a $30 transaction. Submit. Overall balance is 0.
- Update budget to $50. 
- Entered a new $20 transaction. The Overall balance is 0 which is the expected output.

**Comment by ShrutiR5** [comment] 2020-06-04 00:17
Added a screenshot.

**Comment by ShrutiR5** [comment] 2020-06-04 00:18
Sorry that update! thing wasn't very clear, i would recommend showcasing it as an actual button or hyperlink of some sort. Just realized I never clicked the update button.

**Comment by thoalala** [comment] 2020-06-04 00:35
Designers: Do you think the update! should be a button or leave as is. Granted, users can simply enter the daily budget and press enter without pressing the button and it would still work. We only added the update! to help guide the users. 

If we want to change it, developers could you turn the update! into a button or make it look like a button? If this is not possible, let's marked this as not a real failure and closed.

**Comment by angelashen0607** [comment] 2020-06-08 07:53
If we want to change it, I think we can put the word "update!" smaller and in the text box that user uses to input daily budget if possible. That way it connects the usability and design so that users know the "update" button is related to changing the overall budget. The following is an example of how we can do it: 

<img width="743" alt="Screen Shot 2020-06-08 at 12 50 07 AM" src="https://user-images.githubusercontent.com/46581147/84005601-3a47fd00-a922-11ea-93ca-a8c2d6da4882.png">

If we want to do this, then the "update!" font size is 9 or 10 (depends on how big the entry box is) and opacity is set to be 70%.

**Comment by thoalala** [comment] 2020-06-08 16:24
As a team, we decided to not change the update button because this is not a real system failure. Our designer did consider an edit that may be added in the future - just not in the scope of this class.

**Closed as completed by thoalala** 2020-06-08 16:24 UTC
Labels: non-failure
