### ISSUE TITLE
MAJOR: Overall Balance & Date Issue

### ISSUE THREAD

**Issue by ShrutiR5** [BeckMillet/INFO442Team5#49] opened 2020-06-04 00:34 UTC
**Describe the bug**
Though I change the date, the daily total balance does not update. Therefore, money spent on different days affected the current dates total balance. 

**To Reproduce**
1. Go to budget set it to $80.
2. Add item name & item total to $60.
3. Scroll down and change transaction date to 6/4/2020.  
4. Submit it.
5. Add a new item name and item total of $20 and set date to 6/6/2020.
6. Submit it.
7. Error: Total balance is $0, even though these transactions should affect the selected dates, not the current date. 

**Expected behavior**
The daily balance should update based on the date the transaction is entered. This transaction should be deducted from that specific dates budget. 

**Screenshots**
<img width="248" alt="Screen Shot 2020-06-03 at 5 30 15 PM" src="https://user-images.githubusercontent.com/35204568/83702069-6f6deb80-a5c0-11ea-9226-4b019625ebba.png">

**Smartphone (please complete the following information):**
 - Device: iPhoneX (This application is designed exclusively for this screen size, please set your viewing size to match)

**Additional context**
I am just wondering if users are actually allowed to enter transactions and item information for future dates? If so I am unsure if it's working as expected.

**Comment by thoalala** [comment] 2020-06-04 00:47
Users are currently allowed to enter transactions for future dates haha as tech peeps we advertise it as "its a feature, not a bug!" (Just kidding) 

**Question for team**: Calculating future transactions into the current date's overall balance makes logical sense to me because it does affect the overall balance. However, it proves to be a usability hindrance because users expect the transactions to be deducted from the right date. (rightfully so).  BUT, in the real-world users wouldn't add in a future transaction that they haven't even made yet. It's a weird use-case for us to solve. **Is this actually a bug?**

**Comment by thoalala** [comment] 2020-06-04 01:34
Interesting! Thanks for the bug report.

This may actually be by design as your current balance should reflect any transactions that may have occurred on or after the current date.

To me, this is much like a credit card.

Let's say you go to the store and purchase an item and put it on your credit card. The transaction actually goes into a pending state and will clear at a later date (much like here). However, the transaction you made was still the day you spent it. Even if it clears on a later date, the day it went into your budget should be reflected in the "daily budget".

Whether this is considered a bug or not, it still doesn't break the functionality of how the overall balance is calculated. I would say that its a minor bug.

@ShrutiR5 Does that make sense? This could be fixed in a later release as it may be matter of validating that the transaction entered must be on the current date. Lmk if that makes sense and if you have any questions, I'll be more than happy to help clear up any confusion :D

**Comment by kevin-chiu** [comment] 2020-06-08 16:22
Being allowed to document future transactions does not disrupt or break the functionality of the project. As this issue does not pertain to our requirements, we will not be making changes.

**Closed as completed by kevin-chiu** 2020-06-08 16:22 UTC
Labels: duplicate, non-failure, minor
